### ISSUE TITLE
Use of Redis server as a dependency

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#15]
Hi @andris9 ,

Is **redis** is using  to process the webhooks notifications  in queue process?
what happens if we don't remove the unhandled requests which are already present in the redis. How do we remove those(Unhandled or processed requests) requests from redis?

Thanks in advance.

**Comment by andris9** [comment]
Webhooks are retried a few times and removed from Redis automatically once webhook succeeds or has failed too many times. If you want to see currently queued notifications, you can use this [UI application](https://www.npmjs.com/package/bull-ui). Use the same Redis configuration and configure the app to check for a queue named "notify".

<img width="1060" alt="Screenshot 2020-05-26 at 11 23 38" src="https://user-images.githubusercontent.com/132242/82877832-5cfe0d00-9f43-11ea-863a-e81682e7673b.png">

<img width="1060" alt="Screenshot 2020-05-26 at 11 21 43" src="https://user-images.githubusercontent.com/132242/82877847-62f3ee00-9f43-11ea-985a-05c579243ad3.png">

<img width="1060" alt="Screenshot 2020-05-26 at 11 23 08" src="https://user-images.githubusercontent.com/132242/82877867-69826580-9f43-11ea-8384-b6993e1ef11d.png">

**Comment by Pankaj-Pippin** [comment]
Hi,

Cant we clear the queue via the app , its look like mt redis is filling up with 10 mb of data.

Thanks

**Comment by andris9** [comment]
@Pankaj-Pippin  As said previously, webhook data expires automatically. Static data can not be deleted from Redis as it is required for state syncing. 

* How many accounts do you have signed up to IMAP API?
* Can you set up Bull UI like described in the previous step and verify what is going on with the queue, eg, what are the counters for Waiting, Active, Delayed etc jobs?

**Comment by Pankaj-Pippin** [comment]
Hi,

I am using phpmyredis

![image](https://user-images.githubusercontent.com/23304582/82900846-be8d9e00-9f7a-11ea-8d6f-428305a45c14.png)

you can see lots of data but its not getting removed and if its getting removed then no track of it

I ll also try with the tool you suggested

Thanks

**Comment by andris9** [comment]
All this data is needed to track state, you can’t delete it. Keys for queued data are prefixed with bull:

**Comment by Pankaj-Pippin** [comment]
humm, So lets suppose we have 10 emails in inbox then we have 10 key pair data here in redis.

if i have 1000 email then this data will be very huge.

its like we are saving our inbox in redis ?

**Comment by andris9** [comment]
Unfortunately yes, otherwise it would be impossible to detect which flags have changed or which messages were deleted. For example IMAP does not expose almost any data about deleted emails, you always have to compare your local listing against the listing in IMAP to see which emails got deleted so IMAP API keeps an intermediate listing for these comparisons to detect deleted emails and emit webhooks. IMAP API does not store full messages in Redis, only minimally needed state. Alternatively you would have to store the listing yourself but in that case there wouldn't be any need for IMAP API anymore, as you could handle all operations with any kind of IMAP client module.
