### ISSUE TITLE
Calling IMAP APIs immediately after registering an account 

### ISSUE THREAD

**Issue by tamvoflo** [andris9/imapapi#51]
I have a problem when calling the IMAP APIs e.g mailboxes, messages after calling the register account API.
The account's state is Init then I call other APIs immediately, this API will show the error as the screenshot below
![Kazam_screenshot_00004](https://user-images.githubusercontent.com/68526142/104296669-8381b000-54f4-11eb-8b61-c77322e3ef5c.png)

But wait until the partial sync is completed (a long time with lots of emails) and the state is Connected, I can call it smoothly.

My expected is when the user account is registered, the user can get the messages or mailboxes immediately because my system has a lot of email accounts and I don't know how long to wait for the sync will be completed. 

Do we have the solution to open the box to call APIs and sync parallel ones?

**Comment by andris9** [comment]
IMAP API uses a single IMAP connection per account and due to IMAP protocol limitations you can't use that connection to run commands while initial sync is running.

* IMAP connections are usually limited, eg. max 10 parallel IMAP connections per account in Gmail. So if your Desktop Thunderbird is using already 5 of these then you have only 5 connections available for all other devices/apps. If you require multiple connections then some operations might fail as the connection count is already exhausted. When using a single connection then you do not have such issues - if you can already open a connection then all operations should succeed.
*  IMAP API has to potentially keep up a huge amount of connections if a bunch of accounts are registered (1 connection per each registered account). Desktop apps have to open connections only for limited amount of accounts so there is no need to optimize.

If you need to access partial data faster then use a caching layer, eg store the latest know mailbox info into your database and load the data from that cache if IMAP API is not currently able to handle your requests.

**Comment by tamvoflo** [comment]
@andris9 Can we register an account then connect the account immediately without partial/full sync?

**Comment by andris9** [comment]
Full sync is required. Otherwise there would be no way later to know which messages are new/changed.
