### ISSUE TITLE
General Question about amount of mailboxes

### ISSUE THREAD

**Issue by ricus-zero2one** [andris9/imapapi#57]
Hi @andris9 

As the author of the software, would you say there is any hard limit on how many mailboxes can be connected at once? What are the gotcha's someone should be looking out for? Does more mailboxes = possible longer time between getting notifications?

We are investigating an alternative approach to syncing mailboxes, currently we poll mailboxes every one or two minutes, but it's a bit intensive on the client imap servers. We have about 600 mailboxes that we sync this way. 

Adding 600 to just one instance of imap-api doesn't seem feasible, although I could be wrong, hence my question today :)

Thanks for creating this package, you've really found a nice and clean solution to handling incoming mail in an application. It's working nicely with my tests so far (except some outlook scenarios. With mail it never seems like a one golden solution, always something with some mail provider)

**Comment by andris9** [comment]
The short answer is that you need to test it. If you are not generating a lot of load (eg. downloading all the emails all the time) then most of the time all connections are going to stay on idle and not require any resources.

Currently IMAP API spawns 4 threads to handle IMAP connections. If it seems that your processing threads get overloaded and you have a server with lots of CPU cores, then I guess that number could be made configurable, so that you would be able to increase it.

**Comment by shoaib30** [comment]
@ricus-zero2one if you manage to test it with 600 mailboxes, do share your results. I had a similar question, if I get time I will do some stress testing as well and share the behavior.
