### ISSUE TITLE
Ubuntu Setup

### ISSUE THREAD

**Issue by nhCoder** [andris9/imapapi#66]
i have installed imap api and is running on ubuntu how can i access the from outside .beacause its running on local host.
any help will be appreciated

**Comment by andris9** [comment]
See the "host to bind to" option [here](https://github.com/andris9/imapapi#config-mapping). By default it is localhost. You can change it to some other value (eg. "0.0.0.0") to make it accessible from outside. Make sure to use firewall though to block unwanted connections as anyone who would be able to access this application could manipulate with the registered email accounts.

**Comment by nhCoder** [comment]
Thanks for the help... Got it running.... 
I got another issue....
 after few minutes of inactivity with api
It shows  
`{
  "statusCode": 404,
  "error": "Not Found",
  "message": "Account record was not found for requested ID"
}`
I have to add imap and smtp again. Is there any setting to keep it forever

**Comment by Anton-Petrovskyi** [comment]
@andris9 I have the same issue. I can start the emailengine on ec2 Ubuntu but I can't access the emailengine from outside.

ec2 public IP is: 55.555.55.555

My env variables configs:

export EENGINE_SETTINGS={

	"serviceUrl": "http://127.0.0.1:3000", 
	"gmailRedirectUrl": "http://127.0.0.1:3000/oauth", 
	"outlookRedirectUrl": "http://localhost:3000/oauth",
	"webhooks": "http://localhost:3333/api/email/webhook", 

	"license": "mylicense", 
	"webhooksEnabled": true, 
	"webhookEvents":["messageNew", "messageFailed", "messageSent", "authenticationError", "authenticationSuccess", "connectError", "messageBounce", "messageFailed", "messageDeliveryError"], 
	"notifyText": true, 
	"serviceSecret": "serviceSecret", 
	"gmailEnabled": true, 
	"gmailClientId": "111", 
	"gmailClientSecret": "111", 
	"outlookEnabled": true, 
	"outlookClientId": "111", 
	"outlookClientSecret": "111", 
	"outlookAuthority": "consumers", 
}
export EENGINE_SECRET=mysecret
export EENGINE_HOST=**"0.0.0.0"**
emailengine
EMAIL_ENGINE_PREPARED_TOKEN="$(emailengine tokens issue -d "my token - $(date +%F' /  '%T)" -s "*" --dbs.redis="redis://127.0.0.1:6379/8")"

Log on start:
`{"level":30,"time":1652247374463,"pid":2689,"hostname":"ip-123-45-67-890","tid":7,"component":"api","created":1652247374037,"started":1652247374461,"host":"0.0.0.0","port":3000,"protocol":"http","id":"ip-176-54-32-111:2689:33xxxx","uri":"http://0.0.0.0:3000","address":"0.0.0.0","msg":"server started"}
{"level":20,"time":1652247374466,"pid":2689,"hostname":"ip-111-22-33-444","tid":7,"msg":"Started API server thread","port":3000,"host":"0.0.0.0","maxSize":5242880,"version":"2.20.1"}`

And when I am trying to access `https://55.555.55.555:3000/` it says "This site can’t be reached".
Locally it works. I tried to replace 120.0.0.1 with ec2 IP (55.555.55.555) but I could not even start the emailengine.

What do I miss or what is wrong with my configs?

**Comment by andris9** [comment]
@Anton-Petrovskyi Port 3000 is usually not included in the EC2 security group, you have to make sure that it's listed there. When using Ubuntu I'd suggest using the setup script as shown [here](https://emailengine.app/set-up#ubuntu), this way EmailEngine would be added behind an Nginx reverse proxy on a standard HTTPS port, so that you would not have to edit the security group settings (and it would use HTTPS, not HTTP).

**Comment by Anton-Petrovskyi** [comment]
Wow, so quick response. 
I created a duplicate issue as I was not sure if you will get the notification from the closed issue. 

Thank you, I will try the script and respond in the comments below.

**Comment by andris9** [comment]
@Anton-Petrovskyi  I tried the install script myself just now and it worked fine (used the default Ubuntu suggested by EC2 setup, that's 22.04). Make sure that you run the install script as a root user (that is `sudo su` before running the install command) as the HTTPS setup expects root to be the active user. Also make sure that you have set a DNS domain name for your public IP address because you can't create an HTTPS certificate for an IP address, only for a domain name. Also make sure that the EC2 VPC subnet you use is public, not private (even though if the instance has a public IP attached, it probably is already using a public VPC).
